/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'arkray2' at '15/09/25 2:45' with Gradle 2.7
 *
 * @author arkray2, @date 15/09/25 2:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
